version: '2.1'
services:
   mariadb:
     image: mariadb:10.6
     environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=hellodb
      - MYSQL_USER=hellouser
      - MYSQL_PASSWORD=secret1234
     healthcheck:
      test: mysql --user=hellouser --password=secret1234 -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 10
   api:
     image: kvalitetsit/stakit-backend:latest
     environment:
      - jdbc_url=jdbc:mariadb://mariadb:3306/hellodb
      - jdbc_user=hellouser
      - jdbc_pass=secret1234
      - MAIL_HOST=mail
      - MAIL_PORT=1025
      - MAIL_USER=mail_user
      - MAIL_PASSWORD=mail_password
      - MAIL_FROM=from
      - STATUS_UPDATE_BODY_TEMPLATE=/tmp/body.template
      - STATUS_UPDATE_SUBJECT_TEMPLATE=Subject
      - ADAPTER_API_KEY=API-KEY
     volumes:
      - ./body.template:/tmp/body.template:ro
     depends_on:
      mariadb:
       condition: service_healthy
     ports: 
      - 8080:8080
      - 8081:8081
   documenatation-and-test:
     image: kvalitetsit/stakit-backend-documentation:latest
     environment:
      - BASE_URL=/test
      - 'SERVER_URLS=[{"url": "http://localhost:8080", "name": "StaKIT API"}]'
     ports:
      - 80:8080
   mail:
     image: mailhog/mailhog
